server:
  port: 8089
logging:
  level:
    root: info
minio:
  endpoint: http://minio.srcandy.top
  accessKey: oHllD9UzI00MP33eF3S4
  secretKey: CMRkLjistyc1laAG8MtIyvjqqjKROEsnecqp6ko8
  bucketName: terminal-air
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/terminal_air?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: bwzdc520.
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
mail:
    host: smtp.qq.com
    username: candysly@qq.com
    password: vvmhelpyyglrdhca
    port: 465
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
mybatis:
  type-aliases-package: top.srcandy.communitymanage.model
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml