let themeOptions = [
    {
        label: '深色',
        value: 'dark',
        theme: {
            foreground: "#ECECEC",
            background: "#000000",
            cursor: "#FFFFFF",
            selection: "#4040ff",
            black: "#000000",
            red: "#ff0000",
            green: "#33ff00",
            yellow: "#ffff00",
            blue: "#0066ff",
            magenta: "#cc00ff",
            cyan: "#00ffff",
            white: "#d0d0d0"
        }
    },
    {
        label: '浅色',
        value: 'light',
        theme: {
            foreground: "#2c3e50",
            background: "#ffffff",
            cursor: "#2c3e50",
            selection: "#b2d7fe",
            black: "#000000",
            red: "#cc0000",
            green: "#4e9a06",
            yellow: "#c4a000",
            blue: "#3465a4",
            magenta: "#75507b",
            cyan: "#06989a",
            white: "#d3d7cf"
        }
    },
    {
        label: 'Solarized Light',
        value: 'solarized-light',
        theme: {
            foreground: "#657b83",
            background: "#fdf6e3",
            cursor: "#657b83",
            selection: "#073642",
            black: "#073642",
            red: "#dc322f",
            green: "#859900",
            yellow: "#b58900",
            blue: "#268bd2",
            magenta: "#d33682",
            cyan: "#2aa198",
            white: "#eee8d5"
        }
    },
    {
        label: 'Solarized Dark',
        value: 'solarized-dark',
        theme: {
            foreground: "#839496",
            background: "#002b36",
            cursor: "#839496",
            selection: "#073642",
            black: "#073642",
            red: "#dc322f",
            green: "#859900",
            yellow: "#b58900",
            blue: "#268bd2",
            magenta: "#d33682",
            cyan: "#2aa198",
            white: "#fdf6e3"
        }
    },
    {
        label: 'Serendipity',
        value: 'Serendipity',
        theme: {
            foreground: "#dee0ef",
            background: "#1c1e2d",
            cursor: "#8d8f9e",
            selection: "#2c233d",
            black: "#363847",
            red: "#d1918f",
            green: "#aac9d4", 
            yellow: "#edd5d6",
            blue: "#709bbd", 
            magenta: "#a392dc",
            cyan: "#a0b6e8",
            white: "#c7c7c7",
            brightBlack: "#6b6d7c",
            brightRed: "#d1918f",
            brightGreen: "#aac9d4",
            brightYellow: "#edd5d6",
            brightBlue: "#709bbd",
            brightMagenta: "#a392dc",
            brightCyan: "#a0b6e8", 
            brightWhite: "#ffffff"
        },
    },
    {
        label: "Night Owl",
        value: "Night Owl",
        theme: {
            foreground: "#d6dbe1",
            background: "#011627",
            cursor: "#7fdbca",
            selection: "#4d5b75",
            black: "#011627",
            red: "#e53257",
            green: "#a6e22e",
            yellow: "#f4a261",
            blue: "#7fdbca",
            magenta: "#9c6bc7",
            cyan: "#56d9e4",
            white: "#d6dbe1",
            brightBlack: "#3d4d63",
            brightRed: "#e53257",
            brightGreen: "#a6e22e",
            brightYellow: "#f4a261",
            brightBlue: "#7fdbca",
            brightMagenta: "#9c6bc7",
            brightCyan: "#56d9e4",
            brightWhite: "#ffffff"
        }
    },
    {
        label: "Solarized Dark",
        value: "Solarized Dark",
        theme: {
            foreground: "#839496",
            background: "#002b36",
            cursor: "#93a1a1",
            selection: "#073642",
            black: "#073642",
            red: "#dc322f",
            green: "#859900",
            yellow: "#b58900",
            blue: "#268bd2",
            magenta: "#d33682",
            cyan: "#2aa198",
            white: "#fdf6e3",
            brightBlack: "#586e75",
            brightRed: "#dc322f",
            brightGreen: "#859900",
            brightYellow: "#b58900",
            brightBlue: "#268bd2",
            brightMagenta: "#d33682",
            brightCyan: "#2aa198",
            brightWhite: "#fdf6e3"
        }
    },
    {
        label: "Monokai",
        value: "Monokai",
        theme: {
            foreground: "#f8f8f2",
            background: "#272822",
            cursor: "#f8f8f0",
            selection: "#49483e",
            black: "#272822",
            red: "#f92672",
            green: "#a6e22e",
            yellow: "#f4bf75",
            blue: "#66d9ef",
            magenta: "#ae81ff",
            cyan: "#a1efe4",
            white: "#f8f8f2",
            brightBlack: "#75715e",
            brightRed: "#f92672",
            brightGreen: "#a6e22e",
            brightYellow: "#f4bf75",
            brightBlue: "#66d9ef",
            brightMagenta: "#ae81ff",
            brightCyan: "#a1efe4",
            brightWhite: "#ffffff"
        }
    },
    {
        label: "Dracula",
        value: "Dracula",
        theme: {
            foreground: "#f8f8f2",
            background: "#282a36",
            cursor: "#ff79c6",
            selection: "#44475a",
            black: "#282a36",
            red: "#ff5555",
            green: "#50fa7b",
            yellow: "#f1fa8c",
            blue: "#bd93f9",
            magenta: "#ff79c6",
            cyan: "#8be9fd",
            white: "#f8f8f2",
            brightBlack: "#4d4d4d",
            brightRed: "#ff6e6e",
            brightGreen: "#69ff94",
            brightYellow: "#ffffa5",
            brightBlue: "#d6acff",
            brightMagenta: "#ff92d0",
            brightCyan: "#a4ffff",
            brightWhite: "#ffffff"
        }
    },
    {
        label: "Gruvbox Dark",
        value: "Gruvbox Dark",
        theme: {
            foreground: "#ebdbb2",
            background: "#282828",
            cursor: "#fabd2f",
            selection: "#3c3836",
            black: "#282828",
            red: "#fb4934",
            green: "#b8bb26",
            yellow: "#fabd2f",
            blue: "#83a598",
            magenta: "#d3869b",
            cyan: "#8ec07c",
            white: "#ebdbb2",
            brightBlack: "#928374",
            brightRed: "#fb4934",
            brightGreen: "#b8bb26",
            brightYellow: "#fabd2f",
            brightBlue: "#83a598",
            brightMagenta: "#d3869b",
            brightCyan: "#8ec07c",
            brightWhite: "#ffffff"
        }
    },
    {
        label: "Palenight",
        value: "Palenight",
        theme: {
            foreground: "#f8f8f2",
            background: "#292d3e",
            cursor: "#f8f8f2",
            selection: "#5c6370",
            black: "#292d3e",
            red: "#f07178",
            green: "#c3e88d",
            yellow: "#ffcb6b",
            blue: "#82aaff",
            magenta: "#c792ea",
            cyan: "#89ddff",
            white: "#f8f8f2",
            brightBlack: "#4b5263",
            brightRed: "#f07178",
            brightGreen: "#c3e88d",
            brightYellow: "#ffcb6b",
            brightBlue: "#82aaff",
            brightMagenta: "#c792ea",
            brightCyan: "#89ddff",
            brightWhite: "#ffffff"
        }
    },
    {
        label: "Abyss",
        value: "Abyss",
        theme: {
            foreground: "#b0c0d6",
            background: "#111111",
            cursor: "#ffffff",
            selection: "#444444",
            black: "#111111",
            red: "#ff6c6b",
            green: "#88c0d0",
            yellow: "#f9b6a5",
            blue: "#5fafff",
            magenta: "#7a88d1",
            cyan: "#66b6c3",
            white: "#b0c0d6",
            brightBlack: "#3d3d3d",
            brightRed: "#ff6c6b",
            brightGreen: "#88c0d0",
            brightYellow: "#f9b6a5",
            brightBlue: "#5fafff",
            brightMagenta: "#7a88d1",
            brightCyan: "#66b6c3",
            brightWhite: "#ffffff"
        }
    }
]
export default themeOptions;