server:
  port: 8089
logging:
  level:
    root: info
minio:
  endpoint: https://minio.srcandy.top:9000
  accessKey: oHllD9UzI00MP33eF3S4
  secretKey: CMRkLjistyc1laAG8MtIyvjqqjKROEsnecqp6ko8
  bucketName: terminal-air
management:
  endpoints:
    health:
      show-details: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/terminal_air?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: bwzdc520.
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  data:
    redis:
      host: localhost
      port: 6379
mybatis:
  type-aliases-package: top.srcandy.candyterminal.model
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql