name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      - name: Set up SSH key for scp
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H sh.srcandy.top >> ~/.ssh/known_hosts
      - name: Copy files to remote server
        run: |
          rsync -avz dist/ root@sh.srcandy.top:/etc/Share/terminal_air/
